### ISSUE TITLE
Demo set up failed on EC2

### ISSUE THREAD

**Issue by bjrara** [aws-observability/application-signals-demo#4]
## Issue Description
The demo doesn't work by following the instruction of [EC2 Demo](https://github.com/aws-observability/application-signals-demo?tab=readme-ov-file#ec2-demo).

Services that connected to hsqldb failed to start with the following error messages:
```
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-12-22 01:55:51.794 ERROR 3975 --- [           main] o.s.b.d.LoggingFailureAnalysisReporter   :

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class


Action:

Consider the following:
        If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
        If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).
```

## Steps to reproduce the issue
1. Install config, discovery and admin services
2. Install pet-clinic-frontend
3. Install vets

you will see the failure there.

EC2s are granted with Admin permission, network is ok.

**Comment by pxaws** [comment]
This issue was caused by the jar files are built with one java version but are run with another incompatible java version. I updated the steps to ensure the same java version is used (to avoid this issue): https://github.com/aws-observability/application-signals-demo/pull/5.
