### ISSUE TITLE
cloudwatch observability addon version is old

### ISSUE THREAD

**Issue by hibira** [aws-observability/application-signals-demo#48]
In order to use CloudWatch Application Signals, the Cloudwatch Observability Addon version requires v1.7.0-eksbuild.1, but it's v1.5.1-eksbuild.1 in the readme.

<img width="1033" alt="スクリーンショット 2024-08-16 11 45 47" src="https://github.com/user-attachments/assets/06667508-7b99-4c6f-ba88-8326b8bb8d90">

**Comment by hibira** [comment]
Fixed https://github.com/aws-observability/application-signals-demo/pull/49

**Comment by thpierce** [comment]
PR merged, ty
